### ISSUE TITLE
Trait TestContainerForEach with Scala 3 - Compilation Failure 

### ISSUE THREAD

**Issue by scalauser12** [testcontainers/testcontainers-scala#330]
The following test compiles and runs successfully with Scala 2.13.14. However, it fails to compile with Scala 3.3.3.
```scala
import com.dimafeng.testcontainers.KafkaContainer
import com.dimafeng.testcontainers.scalatest.TestContainerForEach
import org.scalatest.flatspec.AnyFlatSpec

class KafkaSpec extends AnyFlatSpec with TestContainerForEach {

  override val containerDef = KafkaContainer.Def()

  "This test" should "compile and run successfully" in withContainers { kafka =>
    assert(kafka.bootstrapServers.nonEmpty)
  }
}
```
This is the compilation error.
```
[info] compiling 1 Scala source to /Users/***/IdeaProjects/TestConainersScala/target/scala-3.3.3/test-classes ...
[error] -- [E008] Not Found Error: /Users/***/IdeaProjects/TestConainersScala/src/test/scala/test/KafkaSpec.scala:12:17 
[error] 12 |    assert(kafka.bootstrapServers.nonEmpty)
[error]    |           ^^^^^^^^^^^^^^^^^^^^^^
[error]    |     value bootstrapServers is not a member of KafkaSpec.this.Containers
[error] one error found
```

Should the test be modified for Scala 3 or is there a deeper cause for the error?

build.sbt
```
val testcontainersScalaVersion = "0.41.4"
val scalatestVersion = "3.2.19"

ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "3.3.3"

lazy val root = (project in file("."))
  .settings(
    name := "TestContainersScala",
    libraryDependencies ++= testDependencies,
    Test / fork := true
  )

lazy val testDependencies = Seq(
  "com.dimafeng" %% "testcontainers-scala-scalatest" % testcontainersScalaVersion % Test,
  "com.dimafeng" %% "testcontainers-scala-kafka" % testcontainersScalaVersion % Test,
  "org.scalatest" %% "scalatest" % scalatestVersion % Test
)
```

**Comment by scalauser12** [comment]
Answering my own question. The test compiles and runs successfully with Scala 3.3.3 after the type of the variable `containerDef` is added.
```
import com.dimafeng.testcontainers.KafkaContainer
import com.dimafeng.testcontainers.scalatest.TestContainerForEach
import org.scalatest.flatspec.AnyFlatSpec

class KafkaSpec extends AnyFlatSpec with TestContainerForEach {

  override val containerDef: KafkaContainer.Def = KafkaContainer.Def()

  "This test" should "compile and run" in withContainers { container =>
    assert(container.bootstrapServers.nonEmpty)
  }
}
```
